- hosts: host1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "1g"
    es_config:
      node.name: "host1"
      network.host: rodrigoramosgo1c.mylabserver.com
      http.port: 9200
      cluster.name: "test-cluster"
      #cluster.initial_master_nodes: "host1"
      discovery.seed_hosts: "rodrigoramosgo1c.mylabserver.com"
      http.port: 9200
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
     - plugin: ingest-attachment

- hosts: host2
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      node.name: "host2"
      network.host: rodrigoramosgo2c.mylabserver.com
      cluster.name: "test-cluster"
      #cluster.initial_master_nodes: "rodrigoramosgo1c.mylabserver.com"
      discovery.seed_hosts: rodrigoramosgo1c.mylabserver.com
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: ingest-attachment